all:
	gcc -o teste ppos_core.c pingpong-semaphore.c queue.c -Wall
sem:
	gcc -o teste ppos_core.c pingpong-semaphore.c queue.c -Wall
race:
	gcc -o teste ppos_core.c pingpong-racecond.c queue.c -Wall
clean:
	-rm teste 