all:
	gcc -o teste1 ppos_core.c pingpong-tasks1.c -Wall
teste1:
	gcc -o teste1 ppos_core.c pingpong-tasks1.c -Wall
teste2:
	gcc -o teste2 ppos_core.c pingpong-tasks2.c -Wall
teste3:
	gcc -o teste3 ppos_core.c pingpong-tasks3.c -Wall
clean:
	rm teste*