all:
	gcc -o teste ppos_core.c pingpong-contab.c queue.c -Wall
teste1:
	gcc -o teste ppos_core.c pingpong-contab-prio.c queue.c -Wall
teste2:
	gcc -o teste2 ppos_core.c pingpong-contab-prio.c queue.c -Wall
clean:
	-rm teste teste2